<!DOCTYPE HTML>
<html lang="en">
<head>
	<meta charset="UTF-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<link rel='shortcut icon' type='image/x-icon' href='/img/favicon.ico' />
	<script
		src="https://code.jquery.com/jquery-3.2.1.min.js"
		integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
		crossorigin="anonymous"
	></script>	
	<link
		rel='stylesheet'
		href='https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/paper/bootstrap.min.css' />
	<script src='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js'></script>
	<script src='https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.4/lodash.min.js'></script>
	<script
		src='https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.19.3/moment-with-locales.min.js'
	></script>
	<title>Dominos (UK) Voucher Puppet</title>
	<style>
		html {
			position: relative;
			min-height: 100%;
		}
		body {
			/* Margin bottom by footer height */
			margin-bottom: 40px;
		}		
		div.jumbotron {
			box-shadow: 0px 1px 3px 1px #aaa;
			background-color: #fcfcfc;
		}
		img {
			height: 1.5em;
		}
		div.jumbotron > div.container > h1 > span {
			vertical-align: middle;
		}
		div.jumbotron > div.container > p {
			margin-left: 120px;
		}
		.footer {
			height: 40px;
			text-align: center;
			position: absolute;
			bottom: 0;
			width: 100%;
		}	
		.valign-fix {
			display: inline-block;
			height: 100%;
			vertical-align: middle
		}
		.valign-middle {
			vertical-align: middle
		}
	</style>
</head>
<body>
<div class="jumbotron">
	<div class="container">
		<h1><img src="img/dominos_logo.png" /> <span>Dominos (UK) Voucher Puppet</span></h1>
		<p>scan for working voucher codes by postcode</p>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<form id="voucher-search">
				<div class="form-group">
					<input
						type="text" class="form-control" id="inputPostcode" 
						placeholder="Enter postcode..." required
					/>
				</div>
				<button 
					id="voucher-search-submit" type="submit" class="btn btn-default"
				>Search</button>
			</form>
		</div>
	</div>
	<div class="row" id="error-row" style="display: none">
		<div class="col-md-12">
			<div class="alert alert-danger alert-dismissible" role="alert">
				<button 
					type="button" class="close" data-dismiss="alert" aria-label="Close"				
				><span aria-hidden="true">&times;</span></button>
				<strong><span id="error-text"></span></strong> 
			</div>
		</div>
	</div>		
</div>
<div id="search-results" class="container" style="visibility: hidden">
	<hr />
	<div class="row">
		<div class="col-md-4">
			<dl id="last-updated">
				<dt>Vouchers list is up to date</dt>
				<dd id="vouchers-uptodate"></dd>
				<dt>Local branch for <span class='postcode-search'></span> is known</dt>
				<dd id="branch-known"></dd>
				<dt>Working vouchers for <span class='postcode-search'></span> up to date</dt>
				<dd id="working-uptodate"></dd>
				<dt>Vouchers list last updated</dt>
				<dd id="vouchers-last-updated"></dd>
				<dt>Working <span class='postcode-search'></span> vouchers last updated</dt>
				<dd id="branch-last-updated"></dd>
			</dl>
		</div>

		<div class="col-md-8">
			<h5>Vouchers</h5>
			<h6>
				<span class="valign-fix"></span>
				<span id="bot-status"  class="valign-middle"></span>
				<img id="loader" src="/img/loader.gif"> 
			</h6>
			<dl id="voucher-list">
			</dl>
		</div>
	</div>
</div>
<footer class="footer">
	<span class="valign-fix"></span>
	<span class="text-muted valign-middle">
		Vouchers scraped from <a href="https://www.hotukdeals.com/">hotukdeals</a> 
		&nbsp;&bull;&nbsp;
		Source available 
		<a href='https://github.com/feltech/DominosVoucherPuppeteer'>on github</a>
	</span>
</footer>
<script>
	(function () {
		var $botStatus = $('#bot-status'),
			$branchKnown = $('#branch-known'),
			$branchLastUpdated = $('#branch-last-updated'),
			$errorRow = $('#error-row'),
			$errorText =$('#error-text'),
			$loader = $('#loader'),
			$postcodes = $('.postcode-search'),
			$voucherList = $('#voucher-list'),
			$voucherSearchSubmit = $('#voucher-search-submit'),
			$vouchersLastUpdated = $('#vouchers-last-updated'),
			$vouchersUpToDate = $('#vouchers-uptodate'),
			$workingUpToDate = $('#working-uptodate'),
			tmpl = _.template(
				'<% _.forEach(vouchers, function (voucher) { %>' +
					'<dt><%= voucher.code %></dt><dd><%- voucher.description %></dd>' +
				'<% }); %>'),
			branchLastClosed,
			timerHandle;

		function check(postcode) {
			$.getJSON("/uptodate/" + postcode).then(function (status) {
				if (status.vouchersLastUpdated) {
					$vouchersLastUpdated.html(
						moment(status.vouchersLastUpdated * 1000).fromNow()
					);
				} else {
					$vouchersLastUpdated.html("never");
				}
				
				if (status.branchLastUpdated) {
					$branchLastUpdated.html(
						moment(status.branchLastUpdated * 1000).fromNow()
					);
				} else {
					$branchLastUpdated.html("never");
				}

				$loader.css('visibility', 'hidden');

				$vouchersUpToDate.html(status.vouchersUpToDate ? "yes" : "no");
				$branchKnown.html(status.branchLastUpdated !== null ? "yes" : "no");
				$workingUpToDate.html(status.branchUpToDate ? "yes" : "no");

				if (status.error) {
					return error(
						"The Dominos bot broke down.", 
						"The dominos bot is poorly. The boss has been notified." +
						" Please try again later."
					);			
				} else if (status.branchExists === false) {
					return error(
						"No local Dominos branch found.", 
						"Sorry, no local Dominos branch was found for that postcode"
					);						
				} else if (
					branchLastClosed !== null && status.branchLastClosed > branchLastClosed 
				) {
					return error(
						"Local Dominos branch is closed.", 
						"Sorry, your local Dominos branch is currently closed, so the bot can't" +
						" check if vouchers are working."
					);	
				} else if (status.updating === "vouchers") {
					$botStatus.html("Updating the main voucher list...");
				} else if (status.updating === "branch") {
					$botStatus.html("Locating your local branch...");
				} else if (status.updating === "working") {
					$botStatus.html("Checking for working vouchers...");
				} else if ($botStatus.html() === "") {
					$botStatus.html("Waiting for bot to be free...");
				}

				branchLastClosed = status.branchLastClosed;

				if (!status.vouchersUpToDate || !status.branchUpToDate) {
					$loader.css('visibility', 'visible');
					timerHandle = setTimeout(function() {
						check(postcode);
					}, 5000);

				} else {
					$botStatus.html("Done");

					$.getJSON("/working/" + postcode).then(function (working) {
						$botStatus.html("Found " + working.length + " working vouchers.");
						render(working);
					});
				}
				$('#search-results').css('visibility', 'visible');
			});
		}

		$('#voucher-search').on('submit', function () {
			var postcode =
				document.getElementById('inputPostcode').value.toUpperCase().replace(/ /g, "");

			$voucherSearchSubmit.attr('disabled', true);
			$voucherList.empty();
			$postcodes.html(postcode);
			$errorRow.css('display', 'none');
			$botStatus.html("");

			branchLastClosed = null;
			clearTimeout(timerHandle);

			$.getJSON("/working/" + postcode).then(function (working) {
				render(working);
				check(postcode);
			}, function error(xhr) {
				$errorText.html(xhr.responseText || "Unkown error");
				$errorRow.css('display', 'initial');
			}).always(function () {
				$voucherSearchSubmit.removeAttr('disabled');
			});

			return false;
		});

		function render(vouchers) {
			$voucherList.empty();
			if (vouchers.length)
				$voucherList.append($(tmpl({vouchers: vouchers})));
			else
				$voucherList.append($('<dt>no vouchers found, yet</dt>'));
		}		

		function error(short, long) {
			$botStatus.html(short);
			$errorText.html(long);
			$errorRow.css('display', 'initial');	
		}
	}());
</script>
</body>
</html>